[package]
name = "tarang"
version = "0.1.0"
edition = "2024"

[dependencies]
aide = { version = "0.15.1", features = ["axum", "axum-multipart", "swagger"] }
axum = { version = "0.8.9", features = ["multipart"] }
axum-jsonschema = { version = "0.9.1", features = ["aide"] }
chrono = "0.4.45"
feed-rs = "2.4.0"
form_urlencoded = "1"
futures = "0.3.33"
opml = "1.1.6"
regex = "1.13.1"
reqwest = "0.13.4"
schemars = "0.9"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_with = "3.22.0"
sqlx = { version = "0.9.0", features = ["runtime-tokio", "sqlite"] }
thiserror = "2.0.19"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
toml = "1.1.4"
tower-http = { version = "0.6.11", features = ["cors"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
