[package]
name = "tarang"
version = "0.1.0"
edition = "2024"

[dependencies]
feed-rs = "2.4.0"
jiff = "0.2.35"
reqwest = "0.13.4"
sqlx = { version = "0.9.0", features = ["runtime-tokio", "sqlite"] }
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1", features = ["v4"] }
